module.exports = {
  invites: require('./invites'),
  user_events: require('./user_events'),
  events: require('./events'),
  users: require('./users'),
  profiles: require('./profiles'),
  careers: require('./careers'),
  genders: require('./genders'),
  religions: require('./religions'),
  political_parties: require('./political_parties'),
  employment_status: require('./employment_status'),
  pets: require('./pets'),
  hobbies: require('./hobbies'),
  searches: require('./searches'),
  photos: require('./photos'),
  favorites: require('./favorites'),
};
